# config
cover: /img/img-bg.jpg
logo: /img/logo.svg
bio: 省略

# Content
excerpt_link: Read More

# Header  nav
menu:
  Home: /
  Archive: /archive
  Images: /images
  Wiki: /wiki/
  Favorites: /favorites
  contact: /about/

##Private: /private

# nav.fonticon.css
navclass:
  Home: icon-home
  Archive: icon-news
  Images: icon-image
  Wiki: icon-wiki
  Favorites: icon-Favorites
  contact: icon-mail

##Private: icon-lock
rss: /atom.xml

# Miscellaneous
google_analytics:
favicon: /img/ice.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
