#Header
menu:
  主页: /
  所有文章: /archives
  随感: /categories/随感
  图片: /picture/index.html
# SubNav
subnav:
  github: "https://github.com/jiangzhendong"
  weibo: "#"
  rss: "#"
  #facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
google_analytics: 'UA-57948559-1'
favicon: /img/ice.ico

#你的头像
avatar: "http://himg.bdimg.com/sys/portrait/item/fb00e58aa8e6bcabe59c9fe58caa3731346622.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
duoshuo_shortname: jwind
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
# 奥巴马的博客: http://localhost:4000/
# 卡卡的美丽传说: http://localhost:4000/
# 本泽马的博客: http://localhost:4000/
# 吉格斯的博客: http://localhost:4000/
# 习大大大不同: http://localhost:4000/
# 托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 本人毕业与2014年，这是一个历史性的年代，标志笔者开始步入这个程序世界的开始年代。
