# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: /default_images/page_background.jpg
post_background: /default_images/post_background.jpg
title_plancehold: 随笔
author:
  head: /default_images/author_head.gif
  signature: Only when you plant the flowers can you really smell their fragrance.
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr]
social:
  - name: GitHub
    icon: github
    link: http://github.com/BoizZ
  - name: Weibo
    icon: weibo
    link: http://weibo.com/heqibang
  - name: SegmentFault
    icon: segmentfault
    link: http://www.segmentfault.com/u/bon
# Duoshuo
duoshuo:
  enable: true
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true