<!-- JiaThis Button BEGIN -->
<!--<div class="jiathis_style">
<a href="" class="jiathis jiathis_txt" target="_blank"><img src="http://v2.jiathis.com/code_mini/images/btn/v1/jiathis1.gif" border="0" /></a>
<a class="jiathis_counter_style_margin:0px 0 0 0px"></a>
<a class="jiathis_like_tsina"></a>
</div>-->
<script type="text/javascript">
/*
var jiathis_config={
	data_track_clickback:false,
	siteNum:12,
	sm:"weixin,qzone,cqq,twitter,tsina,fb,copy,ishare",
	summary:"",
	shortUrl:true,
	hideMore:false
}
function setShare(title, url, summary) {
	var t = title || encodeURI('{{page_title()}}');
	var u = url || '{{ url_for_lang(page.path) }}';
	var s = summary || encodeURI('{{ strip_html(page_excerpt()) }}');
	jiathis_config.title = t;
	jiathis_config.url = u;
	jiathis_config.summary = s;
	//location.href = 'http://www.jiathis.com/share?uid={{theme.share.jiathis.uid}}'
	alert(u);
	return false;
}*/
</script>
<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js?uid={{theme.share.jiathis.uid}}" charset="utf-8"></script>
<!-- JiaThis Button END -->