# Page unique id, see scripts/helper.js#page_uid()
# 页面唯一id设置，影响到评论等第三方系统，页面唯一id的原始值为页面的当前路径
page_uid:
  hash: true # 是否加密，加密后的uid没有特殊字符，推荐使用此项。
  combined: true #是否合并多语言uid，true则多语言页面使用相同的uid
# 当文章有修改时，是否在标题后面显示“new”并且高亮最后修改日期
page_new: false

# script and css，站点使用的全局脚本及css文件
js_css:
- url: //cdn.bootcss.com/jquery/2.2.0/jquery.min.js
- url: //cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap-theme.min.css
- url: //cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/css/bootstrap-material-design.min.css
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/css/ripples.min.css
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/js/material.min.js
#- url: //cdn.bootcss.com/bootstrap-material-design/0.5.10/js/ripples.min.js
- url: //cdn.bootcss.com/sidr/2.2.1/jquery.sidr.min.js
- url: js/jquery.bootstrap-autohidingnavbar.min.js
- url: //cdn.bootcss.com/sidr/2.2.1/stylesheets/jquery.sidr.dark.min.css
- url: //cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css
- url: //cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js
- url: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js
- url: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
- url: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-buttons.css
- url: //cdn.bootcss.com/fancybox/2.1.5/helpers/jquery.fancybox-buttons.js
- url: //cdn.bootcss.com/zclip/1.1.2/jquery.zclip.min.js
- url: css/nova_font.css
- url: css/bs/nova.css
#- url: js/script.js

# menu, all menu name must be translated, see language/lang.yml
menu:
- name: home
  url: /
- name: project
  url: /p/
- name: category
  url: /categories/
- name: archive
  url: /archives/
- name: donate
  url: /donate/
- name: about
  url: /about/

# post widgets. see layout/post/widget_xxx.swig
post_widgets:
#  - search
  - announce
  - ds_recent_visitors
  - about
  - category
  - tag
#  - archive
#  - recent_posts
  - ds_hot
  - ds_recent_comments
  - links

# TODO fetch widgets use ajax, widgets e.g. tag, archive, is sample in all pages.
# used ajax to get widget_xxx contents dynamicly to avoid change all pages.
#
post_widgets_ajax: true
post_widgets_show_count: true
post_widgets_recent_count: 5
# widget links, url is required, name and icon is optional, the icon can be relative or absolute path.
post_widgets_links:
  - name: Jamling's Blog
    url: http://life.ieclipse.cn
    icon: /image/logo.png

# about
about:
  name: Jamling
  github: Jamling
  email: li.jamling@gmail.com
  twitter: JamlingLi
  weibo: Jamling
  desc: 欢迎点击以下图标关注我或与我互动！

# archive
archive:
  type: yearly #yearly|monthly(defaut) see list_archives options
  order: -1 # 1(asc)|-1(desc) defaut desc
  format: YYYY
  show_count: false # true|false, defaut true
  amount: 5 # amount in post widgets

# toc
toc:
  post: true
  project: true
  page: true
# donate
donate:
  enable: true # whether enable page donate

# github removed see hexo-generator-github.

##评论功能设置，目前支持disqus、多说和友言
comments:
  enable: true
  using: duoshuo
  uyan:
    su: path #path|source
    uid: 2064663
  duoshuo:
    short_name: ieclipse
  disqus:
    shortname: ieclipse

# comments的补充，文章阅读数保存在leanclound上
lc:
  enable: true # true|false
  class: Counter # leanclound上的class名称
  app_id: rYUER9KxmGUXSpfEtu7wCFMo-gzGzoHsz
  app_key: k7hzTkcS0blxgry4VT9rJjYj

## share
share:
  jiathis:
    uid: 2064663
## 站点分析统计代码功能组件，本主题提供了google统计和baidu统计
analytics:
  enable: false #
  using: baidu
  baidu:
    id: d028209965ae024527844754f50cbd94
  google:
    id:

## search
search:
  baidu:
    verified: true # false使用极速搜索，无需验证站点；true使用自定义搜索，可以定制高级功能
    site: www.ieclipse.cn # 你的站点名称，极速搜索要用到
    sid: "11812712506721118476" #如不清楚，将baidu_search_script.swig里面的script全部替换掉
    domain: //search.ieclipse.cn #CNAME到zhannei.baidu.com的域名，未配置留空

rss: atom.xml

# icp
icp: 苏ICP备15019510号

## css
node_sass:
  outputStyle: nested

# grid layout
layout:
  index: # index some to post.
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    widgets: col-sx-12 col-sm-4 col-md-3 col-lg-3 #hidden-xs
  page: #common page
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    toc: col-sx-12 col-sm-4 col-md-3 col-lg-3 hidden-xs
  p: #project
    sidebar: col-sx-12 col-sm-12 col-md-2 col-lg-2
    main: col-sx-12 col-sm-8 col-md-8 col-lg-8
    toc: col-sx-2 col-sm-2 col-md-2 col-lg-2 hidden-xs
  d: #donates
    main: col-sx-12 col-sm-8 col-md-9 col-lg-9
    top: col-sx-6 col-sm-4 col-md-3 col-lg-3
